version: '3.7'

x-env-defaults: &env
  NODE_ENV: development
  YARN_CACHE_FOLDER: /.yarn-cache

x-env-core: &env-core
  MONGO_URL: ${MONGO_URL-mongodb://root:password123@mongodb-primary:27017,mongodb-secondary:27017/?authSource=admin&readPreference=primary}
  TOKEN_SECRET: ${TOKEN_SECRET-thisisnotsecretdonotuse}

x-node-defaults: &node
  tty: true
  init: true
  image: node:16.13-alpine
  working_dir: /sso
  volumes:
    - .:/sso:cached
    - ./node_modules:/sso/node_modules:delegated
    - yarn-cache:/.yarn-cache
  environment:
    <<: *env

services:
  app:
    <<: *node
    working_dir: /sso/app
    entrypoint: ["yarn"]
    command: ["dev"]
    environment:
      <<: *env
      HOST: sso.dev.parameter1.com
      PORT: 7913
      VITE_GRAPHQL_URL: ${VITE_GRAPHQL_URL-http://sso.dev.parameter1.com:7912/graphql}
    depends_on:
      - graphql
    ports:
      - "7913:7913"
    hostname: sso.dev.parameter1.com

  cli:
    <<: *node
    working_dir: /sso/cli
    entrypoint: ["node"]
    command: ["src/index.js"]
    environment:
      <<: [*env, *env-core]
    depends_on:
      - mongodb-secondary

  commands:
    <<: *node
    entrypoint: ["tail"]
    command: ["-f", "/dev/null"]

  graphql:
    <<: *node
    working_dir: /sso/graphql
    entrypoint: ["yarn"]
    command: ["dev"]
    environment:
      <<: [*env, *env-core]
      APP_URL: ${APP_URL-http://sso.dev.parameter1.com:7913/app}
      EXPOSED_HOST: sso.dev.parameter1.com
      EXPOSED_PORT: 7912
      HOST: sso.dev.parameter1.com
      SENDGRID_API_KEY: ${SENDGRID_API_KEY-}
    ports:
      - "7912:80"
    hostname: sso.dev.parameter1.com
    depends_on:
      - mongodb-secondary

  lib:
    <<: *node
    working_dir: /sso/lib
    entrypoint: ["yarn"]
    command: ["dev"]
    environment:
      <<: *env
      HOST: test-sso-app.dev.parameter1.com
      PORT: 7914
    ports:
      - "7914:7914"
    hostname: test-sso-app.dev.parameter1.com

  mongodb-primary:
    image: bitnami/mongodb:5.0
    environment:
      - MONGODB_ADVERTISED_HOSTNAME=mongodb-primary
      - MONGODB_REPLICA_SET_MODE=primary
      - MONGODB_ROOT_PASSWORD=password123
      - MONGODB_REPLICA_SET_KEY=tenancy
    volumes:
      - mongodb-primary:/bitnami
    ports:
      - "7910:27017"

  mongodb-secondary:
    image: bitnami/mongodb:5.0
    depends_on:
      - mongodb-primary
    environment:
      - MONGODB_ADVERTISED_HOSTNAME=mongodb-secondary
      - MONGODB_REPLICA_SET_MODE=secondary
      - MONGODB_PRIMARY_HOST=mongodb-primary
      - MONGODB_PRIMARY_ROOT_PASSWORD=password123
      - MONGODB_REPLICA_SET_KEY=tenancy
    volumes:
      - mongodb-secondary:/bitnami

  service:
    <<: *node
    working_dir: /sso/service
    entrypoint: ["yarn"]
    command: ["dev"]
    environment:
      <<: [*env, *env-core]
      EXPOSED_HOST: sso-service.dev.parameter1.com
      EXPOSED_PORT: 7911
      HOST: sso-service.dev.parameter1.com
    ports:
      - "7911:80"
    hostname: sso-service.dev.parameter1.com
    depends_on:
      - mongodb-secondary

volumes:
  yarn-cache: {}
  mongodb-primary: {}
  mongodb-secondary: {}
