version: '3.7'

x-env-defaults: &env
  NODE_ENV: development
  YARN_CACHE_FOLDER: /.yarn-cache

x-env-core: &env-core
  MONGO_URL: ${MONGO_URL-}
  TOKEN_SECRET: ${TOKEN_SECRET-thisisnotsecretdonotuse}

x-node-defaults: &node
  tty: true
  init: true
  image: node:16.15-alpine
  working_dir: /sso
  volumes:
    - .:/sso:cached
    - ./node_modules:/sso/node_modules:delegated
    - yarn-cache:/.yarn-cache
  environment:
    <<: *env

services:
  app:
    <<: *node
    working_dir: /sso/app
    entrypoint: ["yarn"]
    command: ["dev"]
    environment:
      <<: *env
      HOST: sso.dev.parameter1.com
      PORT: 7913
      VITE_GRAPHQL_URL: ${VITE_GRAPHQL_URL-http://sso.dev.parameter1.com:7912/graphql/managed}
    depends_on:
      - graphql-managed
    ports:
      - "7913:7913"
    hostname: sso.dev.parameter1.com

  change-manager:
    <<: *node
    working_dir: /sso/services/change-manager
    entrypoint: ["yarn"]
    command: ["dev"]
    environment:
      <<: [*env, *env-core]

  cli:
    <<: *node
    working_dir: /sso/cli
    entrypoint: ["node"]
    command: ["src/index.js"]
    environment:
      <<: [*env, *env-core]

  commands:
    <<: *node
    entrypoint: ["tail"]
    command: ["-f", "/dev/null"]

  graphql-managed:
    <<: *node
    working_dir: /sso/graphql/managed
    entrypoint: ["yarn"]
    command: ["dev"]
    environment:
      <<: [*env, *env-core]
      APP_URL: ${APP_URL-http://sso.dev.parameter1.com:7913/app}
      EXPOSED_HOST: sso.dev.parameter1.com
      EXPOSED_PORT: 7912
      HOST: sso.dev.parameter1.com
      SENDGRID_API_KEY: ${SENDGRID_API_KEY-}
    ports:
      - "7912:80"
    hostname: sso.dev.parameter1.com
    depends_on:
      - change-manager
      - materializer

  graphql-materialized:
    <<: *node
    working_dir: /sso/graphql/materialized
    entrypoint: ["yarn"]
    command: ["dev"]
    environment:
      <<: [*env, *env-core]
      EXPOSED_HOST: sso.dev.parameter1.com
      EXPOSED_PORT: 7915
      HOST: sso.dev.parameter1.com
    ports:
      - "7915:80"
    hostname: sso.dev.parameter1.com

  lib:
    <<: *node
    working_dir: /sso/lib
    entrypoint: ["yarn"]
    command: ["dev"]
    environment:
      <<: *env
      HOST: test-sso-app.dev.parameter1.com
      PORT: 7914
    ports:
      - "7914:7914"
    hostname: test-sso-app.dev.parameter1.com

  materializer:
    <<: *node
    working_dir: /sso/services/materializer
    entrypoint: ["yarn"]
    command: ["dev"]
    environment:
      <<: [*env, *env-core]


volumes:
  yarn-cache: {}
