version: '3.7'

x-env-defaults: &env
  NODE_ENV: development
  YARN_CACHE_FOLDER: /.yarn-cache

x-env-core: &env-core
  MONGO_URL: ${MONGO_URL-mongodb://root:password123@mongodb-primary:27017,mongodb-secondary:27017/?authSource=admin&readPreference=primary}
  TOKEN_SECRET: ${TOKEN_SECRET-thisisnotsecretdonotuse}

x-node-defaults: &node
  tty: true
  init: true
  image: node:16.13-alpine
  working_dir: /tenancy
  volumes:
    - .:/tenancy:cached
    - ./node_modules:/tenancy/node_modules:delegated
    - yarn-cache:/.yarn-cache
  environment:
    <<: *env

services:
  cli:
    <<: *node
    working_dir: /tenancy/cli
    entrypoint: ["node"]
    command: ["src/index.js"]
    environment:
      <<: *env
      <<: *env-core
    depends_on:
      - mongodb-secondary

  commands:
    <<: *node
    entrypoint: ["tail"]
    command: ["-f", "/dev/null"]

  mongodb-primary:
    image: bitnami/mongodb:5.0
    environment:
      - MONGODB_ADVERTISED_HOSTNAME=mongodb-primary
      - MONGODB_REPLICA_SET_MODE=primary
      - MONGODB_ROOT_PASSWORD=password123
      - MONGODB_REPLICA_SET_KEY=tenancy
    volumes:
      - mongodb-primary:/bitnami
    ports:
      - "7910:27017"

  mongodb-secondary:
    image: bitnami/mongodb:5.0
    depends_on:
      - mongodb-primary
    environment:
      - MONGODB_ADVERTISED_HOSTNAME=mongodb-secondary
      - MONGODB_REPLICA_SET_MODE=secondary
      - MONGODB_PRIMARY_HOST=mongodb-primary
      - MONGODB_PRIMARY_ROOT_PASSWORD=password123
      - MONGODB_REPLICA_SET_KEY=tenancy
    volumes:
      - mongodb-secondary:/bitnami

volumes:
  yarn-cache: {}
  mongodb-primary: {}
  mongodb-secondary: {}
