version: '3.7'

x-env-defaults: &env
  NODE_ENV: development
  YARN_CACHE_FOLDER: /.yarn-cache

x-env-mongodb: &env-mongodb
  MONGO_URL: ${MONGO_URL-}

x-env-token: &env-token
  TOKEN_SECRET: ${TOKEN_SECRET-thisisnotsecretdonotuse}

x-env-redis-pubsub: &env-redis-pubsub
  REDIS_PUBSUB_HOST: ${REDIS_PUBSUB_HOST-redis-pubsub}
  REDIS_PUBSUB_PORT: ${REDIS_PUBSUB_PORT-6379}

x-env-entity-message: &env-entity-message
  AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID_ENTITY_MESSAGE}
  AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY_ENTITY_MESSAGE}
  SQS_QUEUE_URL: ${SQS_QUEUE_URL_ENTITY_MESSAGE}

x-node-defaults: &node
  tty: true
  init: true
  image: node:18.12-alpine
  working_dir: /sso
  volumes:
    - .:/sso:cached
    - ./node_modules:/sso/node_modules:delegated
    - yarn-cache:/.yarn-cache
  environment:
    <<: *env

services:
  app:
    <<: *node
    working_dir: /sso/app
    entrypoint: ["yarn"]
    command: ["dev"]
    environment:
      <<: *env
      HOST: sso.dev.parameter1.com
      PORT: 7913
      VITE_GRAPHQL_COMMAND_URL: ${VITE_GRAPHQL_COMMAND_URL-http://graphql.sso.dev.parameter1.com:7912/command}
      VITE_GRAPHQL_QUERY_URL: ${VITE_GRAPHQL_QUERY_URL-http://graphql.sso.dev.parameter1.com:7911/query}
      VITE_GRAPHQL_SUBSCRIPTION_URL: ${VITE_GRAPHQL_SUBSCRIPTIONS_URL-ws://graphql.sso.dev.parameter1.com:7915/subscription}
    depends_on:
      - graphql-command
      - graphql-query
      - graphql-subscription
    ports:
      - "7913:7913"
    hostname: sso.dev.parameter1.com

  cli:
    <<: *node
    working_dir: /sso/cli
    entrypoint: ["node"]
    command: ["src/index.js"]
    environment:
      <<: [*env, *env-mongodb]
      ENTITY_COMMAND_URL: ${ENTITY_COMMAND_URL-http://entity-command}
      USER_URL: ${USER_URL-http://user}
    depends_on:
      - entity-command
      - user

  commands:
    <<: *node
    entrypoint: ["tail"]
    command: ["-f", "/dev/null"]

  entity-command:
    <<: *node
    working_dir: /sso/services/entity-command
    entrypoint: ["yarn"]
    command: ["dev"]
    environment:
      <<: [*env, *env-redis-pubsub, *env-mongodb, *env-entity-message]
      EXPOSED_HOST: services.sso.dev.parameter1.com
      EXPOSED_PORT: 7919
      HOST: services.sso.dev.parameter1.com
    ports:
      - "7919:80"
    hostname: services.sso.dev.parameter1.com
    depends_on:
      - entity-message-poll
      - redis-pubsub

  entity-message-poll:
    <<: *node
    working_dir: /sso/services/entity-message-poll
    entrypoint: ["yarn"]
    command: ["dev"]
    environment:
      <<: [*env, *env-entity-message]
      ENTITY_PROCESSOR_URL: ${ENTITY_PROCESSOR_URL-http://entity-message-processor}
    depends_on:
      - entity-message-processor

  entity-message-processor:
    <<: *node
    working_dir: /sso/services/entity-message-processor
    entrypoint: ["yarn"]
    command: ["dev"]
    environment:
      <<: [*env, *env-redis-pubsub, *env-mongodb]
      EXPOSED_HOST: services.sso.dev.parameter1.com
      EXPOSED_PORT: 7918
      HOST: services.sso.dev.parameter1.com
    ports:
      - "7918:80"
    hostname: services.sso.dev.parameter1.com
    depends_on:
      - redis-pubsub

  user:
    <<: *node
    working_dir: /sso/services/user
    entrypoint: ["yarn"]
    command: ["dev"]
    environment:
      <<: [*env, *env-mongodb, *env-entity-message, *env-token]
      APP_URL: ${APP_URL-http://sso.dev.parameter1.com:7913}
      EXPOSED_HOST: services.sso.dev.parameter1.com
      EXPOSED_PORT: 7920
      HOST: services.sso.dev.parameter1.com
      SENDGRID_API_KEY: ${SENDGRID_API_KEY-}
    ports:
      - "7920:80"
    hostname: services.sso.dev.parameter1.com

  graphql-command:
    <<: *node
    working_dir: /sso/graphql/command
    entrypoint: ["yarn"]
    command: ["dev"]
    environment:
      <<: [*env, *env-mongodb]
      MONGO_URL: ${MONGO_URL_COMMAND}
      EXPOSED_HOST: graphql.sso.dev.parameter1.com
      EXPOSED_PORT: 7912
      HOST: graphql.sso.dev.parameter1.com
    ports:
      - "7912:80"
    hostname: graphql.sso.dev.parameter1.com

  graphql-query:
    <<: *node
    working_dir: /sso/graphql/query
    entrypoint: ["yarn"]
    command: ["dev"]
    environment:
      <<: [*env, *env-mongodb]
      MONGO_URL: ${MONGO_URL_QUERY}
      EXPOSED_HOST: graphql.sso.dev.parameter1.com
      EXPOSED_PORT: 7911
      HOST: graphql.sso.dev.parameter1.com
    ports:
      - "7911:80"
    hostname: graphql.sso.dev.parameter1.com

  graphql-subscription:
    <<: *node
    working_dir: /sso/graphql/subscription
    entrypoint: ["yarn"]
    command: ["dev"]
    environment:
      <<: [*env, *env-mongodb, *env-redis-pubsub]
      MONGO_URL: ${MONGO_URL_SUBSCRIPTION}
      EXPOSED_HOST: graphql.sso.dev.parameter1.com
      EXPOSED_PORT: 7915
      HOST: graphql.sso.dev.parameter1.com
    ports:
      - "7915:80"
    depends_on:
      - redis-pubsub
    hostname: graphql.sso.dev.parameter1.com

  lib:
    <<: *node
    working_dir: /sso/lib
    entrypoint: ["yarn"]
    command: ["dev"]
    environment:
      <<: *env
      HOST: test-sso-app.dev.mindfulcms.com
      PORT: 7914
    ports:
      - "7914:7914"
    hostname: test-sso-app.dev.mindfulcms.com

  redis-pubsub:
    tty: true
    image: redis:7.0-alpine
    ports:
      - "7910:6379"

volumes:
  yarn-cache: {}
