version: '3.7'

x-env-defaults: &env
  NODE_ENV: development
  YARN_CACHE_FOLDER: /.yarn-cache

x-env-core: &env-core
  MONGO_URL: ${MONGO_URL-}
  TOKEN_SECRET: ${TOKEN_SECRET-thisisnotsecretdonotuse}

x-env-redis-pubsub: &env-redis-pubsub
  REDIS_PUBSUB_HOST: ${REDIS_PUBSUB_HOST-redis-pubsub}
  REDIS_PUBSUB_PORT: ${REDIS_PUBSUB_PORT-6379}

x-node-defaults: &node
  tty: true
  init: true
  image: node:16.15-alpine
  working_dir: /sso
  volumes:
    - .:/sso:cached
    - ./node_modules:/sso/node_modules:delegated
    - yarn-cache:/.yarn-cache
  environment:
    <<: *env

services:
  app:
    <<: *node
    working_dir: /sso/app
    entrypoint: ["yarn"]
    command: ["dev"]
    environment:
      <<: *env
      HOST: sso.dev.parameter1.com
      PORT: 7913
      VITE_GRAPHQL_COMMAND_URL: ${VITE_GRAPHQL_COMMAND_URL-http://graphql.sso.dev.parameter1.com:7912/command}
      VITE_GRAPHQL_SUBSCRIPTIONS_URL: ${VITE_GRAPHQL_SUBSCRIPTIONS_URL-ws://graphql.sso.dev.parameter1.com:7912/subscriptions}
      VITE_GRAPHQL_QUERY_URL: ${VITE_GRAPHQL_QUERY_URL-http://graphql.sso.dev.parameter1.com:7911/query}
    depends_on:
      - graphql-command
      - graphql-query
    ports:
      - "7913:7913"
    hostname: sso.dev.parameter1.com

  cli:
    <<: *node
    working_dir: /sso/cli
    entrypoint: ["node"]
    command: ["src/index.js"]
    environment:
      <<: [*env, *env-core, *env-redis-pubsub]
    depends_on:
      - materializer
      - redis-pubsub

  commands:
    <<: *node
    entrypoint: ["tail"]
    command: ["-f", "/dev/null"]

  graphql-command:
    <<: *node
    working_dir: /sso/graphql/command
    entrypoint: ["yarn"]
    command: ["dev"]
    environment:
      <<: [*env, *env-core, *env-redis-pubsub]
      APP_URL: ${APP_URL-http://sso.dev.parameter1.com:7913}
      EXPOSED_HOST: graphql.sso.dev.parameter1.com
      EXPOSED_PORT: 7912
      HOST: graphql.sso.dev.parameter1.com
      SENDGRID_API_KEY: ${SENDGRID_API_KEY-}
    ports:
      - "7912:80"
    hostname: graphql.sso.dev.parameter1.com
    depends_on:
      - materializer
      - redis-pubsub

  graphql-query:
    <<: *node
    working_dir: /sso/graphql/query
    entrypoint: ["yarn"]
    command: ["dev"]
    environment:
      <<: [*env, *env-core]
      EXPOSED_HOST: graphql.sso.dev.parameter1.com
      EXPOSED_PORT: 7911
      HOST: graphql.sso.dev.parameter1.com
    ports:
      - "7911:80"
    hostname: graphql.sso.dev.parameter1.com

  lib:
    <<: *node
    working_dir: /sso/lib
    entrypoint: ["yarn"]
    command: ["dev"]
    environment:
      <<: *env
      HOST: test-sso-app.dev.parameter1.com
      PORT: 7914
    ports:
      - "7914:7914"
    hostname: test-sso-app.dev.parameter1.com

  materializer:
    <<: *node
    working_dir: /sso/services/materializer
    entrypoint: ["yarn"]
    command: ["dev"]
    environment:
      <<: [*env, *env-core, *env-redis-pubsub]
    depends_on:
      - redis-pubsub

  redis-pubsub:
    tty: true
    image: redis:7.0-alpine
    ports:
      - "7910:6379"

volumes:
  yarn-cache: {}
